#!/usr/bin/env bash
set -u
output=''
while [ "$#" -gt 0 ]; do
  case "$1" in
    --output) output=$2; shift 2 ;;
    *) shift ;;
  esac
done
test -n "$output"
printf '%s' "${MOCK_PAYLOAD:-valid-body}" > "$output"
if [ "${MOCK_MODE:-success}" = failure ]; then
  exit 42
fi
